---
- hosts: localhost
  connection: local
  tasks:

    - name: Get common variables
      include_vars:
        file: "common.yml"
        name: common
      tags:
        - packages
        - config

    - name: Add dnf rpm repositories
      dnf:
        name: "{{ common.dnfrepos }}"
        state: present
      become: yes
      tags:
        - packages

    - name: Add dnf copr repositories
      command:
        cmd: "dnf copr enable -y {{ item.name }}"
        creates: "/etc/yum.repos.d/{{ item.repofile }}"
      with_items: "{{ common.copr }}"
      become: yes
      tags:
        - packages

    - name: Import vscodium gpg key
      rpm_key:
        state: present
        key: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
      become: yes

    - name: Add vscodium repository
      copy:
        src: files/vscodium
        dest: /etc/yum.repos.d/vscodium.repo
      become: yes
      tags:
        - packages

    - name: Add NordVPN Repository
      dnf:
        name: "https://repo.nordvpn.com/yum/nordvpn/centos/noarch/Packages/n/nordvpn-release-1.0.0-1.noarch.rpm"
        state: present
      become: yes
      tags:
        - packages

    - name: Install common packages
      dnf:
        name: "{{ common.packages }}"
        state: present
      become: yes
      tags:
        - packages

    - name: Install pip packages
      pip:
        name: "{{ common.pip }}"
        executable: pip3
        extra_args: --user
      tags:
        - packages
        
    - name: Set up nvidia xorg
      copy: 
        src: "files/nvidia-{{ ansible_hostname }}"
        dest: /etc/X11/xorg.conf.d/20-nvidia.conf
      become: yes
      tags:
        - config

    - name: Set up .profile
      copy:
        src: files/profile
        dest: "$HOME/.profile"
      tags:
        - config

    - name: Make sure alacritty folder is present
      file:
        path: "$HOME/.config/alacritty/"
        state: directory
      tags:
        - config

    - name: Set up alacritty config
      copy:
        src: files/alacritty.yml
        dest: "$HOME/.config/alacritty/alacritty.yml"
      tags:
        - config
    
    - name: Make sure i3 folder is present
      file:
        path: "$HOME/.config/i3/"
        state: directory
      tags:
        - config

    - name: Set up i3 config
      copy:
        src: files/i3config
        dest: "$HOME/.config/i3/config"
      tags:
        - config

    - name: Move battery services
      copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      become: yes
      with_items:
        - ac.target
        - battery.target
        - governor.service

    - name: Move governor file
      copy:
        src: "files/update_governor.sh"
        dest: "/usr/bin/update_governor"
        mode: 0755
      become: yes

    - name: Enable governor service
      systemd:
        enabled: yes
        name: governor.service
      become: yes

    - name: Set up flathub
      flatpak_remote:
        name: flathub
        flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
      become: yes
      tags:
        - packages

    - name: Install flatpaks
      flatpak:
        name: "{{ item.name }}"
        remote: "{{ item.remote }}"
        state: present
      with_items: "{{ common.flatpak }}"
      tags:
        - packages

    - name: Make flatpak executables
      blockinfile:
        path: "/usr/bin/{{ item.executable }}"
        create: yes
        mode: 0755
        block: |
          #!/bin/bash
          flatpak run {{ item.name }}
      with_items: "{{ common.flatpak }}"
      become: yes

    - name: Install pdfannots
      copy:
        src: files/pdfannots
        dest: /usr/bin/pdfannots
        mode: 0755
      become: yes

    - name: Install rust
      shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
      args:
          creates: $HOME/.cargo
          warn: false

    - name: Install NVM
      shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | /bin/bash"
      args: 
          creates: $HOME/.config/nvm
          warn: false

    - name: Install RVM
      shell: "curl -sSL https://get.rvm.io | /bin/bash -s stable --ruby -- --ignore-dotfiles"
      args: 
          creates: $HOME/.rvm
          warn: false

    - name: Set up Mate dconf
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value | string }}"
      with_items:
        - key: "/org/mate/desktop/session/required-components-list"
          value: "['windowmanager','panel']"
        - key: "/org/mate/desktop/session/required-components/windowmanager"
          value: '"i3"'

    - include_tasks: "hosts/{{ ansible_hostname }}.yml"
