---
- hosts: localhost
  connection: local
  tasks:

    - name: Get common variables
      include_vars:
        file: "common.yml"
        name: common
      tags:
        - packages
        - config

    - name: Install common packages
      pacman:
        name: "{{ common.packages }}"
        state: present
      become: yes
      tags:
        - packages

    - name: Install pip packages
      pip:
        name: "{{ common.pip }}"
        executable: pip3
        extra_args: --user
      tags:
        - packages

    - name: Install yay packages
      yay:
          name: "{{ common.yay }}"
          state: present
      tags:
          - packages
        
    - name: Set up nvidia xorg
      copy: 
        src: "files/nvidia-{{ ansible_hostname }}"
        dest: /etc/X11/xorg.conf.d/20-nvidia.conf
      become: yes
      tags:
        - config

    - name: Set up .profile
      copy:
        src: files/profile
        dest: "$HOME/.profile"
      tags:
        - config

    - name: Make sure alacritty folder is present
      file:
        path: "$HOME/.config/alacritty/"
        state: directory
      tags:
        - config

    - name: Set up alacritty config
      copy:
        src: files/alacritty.yml
        dest: "$HOME/.config/alacritty/alacritty.yml"
      tags:
        - config
      when: false
    
    - name: Make sure i3 folder is present
      file:
        path: "$HOME/.config/i3/"
        state: directory
      tags:
        - config

    - name: Set up i3 config
      copy:
        src: files/i3config
        dest: "$HOME/.config/i3/config"
      tags:
        - config

    - name: Set up udev rules for batteries
      copy:
          src: "files/99-powertargets.rules"
          dest: "/etc/udev/rules.d/"
      become: yes
      tags:
          - config

    - name: Move battery services
      copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      become: yes
      with_items:
        - ac.target
        - battery.target
        - governor.service

    - name: Move governor file
      copy:
        src: "files/update_governor.sh"
        dest: "/usr/bin/update_governor"
        mode: 0755
      become: yes

    - name: Enable governor service
      systemd:
        enabled: yes
        name: governor.service
      become: yes

    - name: Install pdfannots
      copy:
        src: files/pdfannots
        dest: /usr/bin/pdfannots
        mode: 0755
      become: yes

    - name: Install rust
      shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
      args:
          creates: $HOME/.cargo
          warn: false

    - name: Install NVM
      shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | /bin/bash"
      args: 
          creates: $HOME/.config/nvm
          warn: false

    - name: Install RVM
      shell: "curl -sSL https://get.rvm.io | /bin/bash -s stable --ruby"
      args: 
          creates: $HOME/.rvm
          warn: false

    - name: Link vim to nvim
      file:
          src: /usr/bin/nvim
          dest: /usr/bin/vim
          state: link
      become: yes

    - include_tasks: "hosts/{{ ansible_hostname }}.yml"
